version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fullstack-app
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: fullstack-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
